repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5
  hooks:
  - id: autopep8
    args:
      - --in-place
      - --aggressive
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
- repo: https://github.com/jazzband/pip-tools
  rev: 6.2.0
  hooks:
    - id: pip-compile
