services:
  pisces-db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres  # name of the application database user
      - POSTGRES_PASSWORD=postgres  # name of the application database user
      - POSTGRES_DB=postgres  # name of the application database
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
  pisces-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8007}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8007}:${APPLICATION_PORT:-8007}"
    depends_on:
      - pisces-db

volumes:
  piscesdbvolume:
