version: '3.1'

services:
  pisces-db:
    image: postgres:10.4
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
  pisces-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    depends_on:
      - pisces-db
    volumes:
      - .:/code
  pisces-cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - /data/logs/cron:/var/log/pisces-cron

volumes:
  piscesdbvolume:
