version: '3'

services:
  pisces-db:
    image: postgres:10.4
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
  pisces-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
      - /data/logs/cron:/data/log/cron
    ports:
      - "8007:8007"
    depends_on:
      - pisces-db

volumes:
  piscesdbvolume:
