version: '3'

services:
  pisces-db:
    image: postgres:10.4
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
  pisces-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8007}
    volumes:
      - .:/code
      - /data/logs/cron:/data/log/cron
    ports:
      - "${APPLICATION_PORT:-8007}:${APPLICATION_PORT:-8007}"
    depends_on:
      - pisces-db

volumes:
  piscesdbvolume:
