# Generated by Django 2.2.18 on 2021-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0006_auto_20201119_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobject',
            name='online_pending',
            field=models.BooleanField(default=False),
        ),
    ]
